// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Query struct {
}
