{{- if .Values.websiteUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "waldritter-website.fullname" . }}-website-ui
  labels:
    {{- include "waldritter-website.websiteUi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.websiteUi.service.type }}
  ports:
    - port: {{ .Values.websiteUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "waldritter-website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: website-ui
{{- end }}