apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waldritter

resources:
  - namespace.yaml
  - rails-api/deployment.yaml
  - rails-api/service.yaml
  - rails-api/pvc.yaml
  - admin-ui/deployment.yaml
  - admin-ui/service.yaml
  - public-ui/deployment.yaml
  - public-ui/service.yaml
  - url-extractor/deployment.yaml
  - url-extractor/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: waldritter
