package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/waldritter/website-content-api/content"
	"github.com/waldritter/website-content-api/graph/generated"
	"github.com/waldritter/website-content-api/graph/model"
)

// Metadata is the resolver for the metadata field.
func (r *pageResolver) Metadata(ctx context.Context, obj *content.Page) (*content.PageMetadata, error) {
	// Metadata is already loaded in the Page object
	return obj.Metadata, nil
}

// Pages is the resolver for the pages field.
func (r *queryResolver) Pages(ctx context.Context) ([]*content.Page, error) {
	pages := r.Store.GetAllPages()
	return pages, nil
}

// Page is the resolver for the page field.
func (r *queryResolver) Page(ctx context.Context, documentID string) (*content.Page, error) {
	page, err := r.Store.GetPage(documentID)
	if err != nil {
		return nil, err
	}
	return page, nil
}

// MenuItems is the resolver for the menuItems field.
func (r *queryResolver) MenuItems(ctx context.Context, pagination *model.PaginationInput) ([]*content.MenuItem, error) {
	items := r.Store.GetMenuItems()

	// Apply pagination if provided
	if pagination != nil && pagination.Limit != nil {
		limit := *pagination.Limit
		offset := 0
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}

		// Handle out of bounds
		if offset >= len(items) {
			return []*content.MenuItem{}, nil
		}

		end := offset + limit
		if end > len(items) {
			end = len(items)
		}

		items = items[offset:end]
	}

	return items, nil
}

// Footer is the resolver for the footer field.
func (r *queryResolver) Footer(ctx context.Context) (*content.Footer, error) {
	footer := r.Store.GetFooter()
	return footer, nil
}

// Page returns generated.PageResolver implementation.
func (r *Resolver) Page() generated.PageResolver { return &pageResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type pageResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
